export enum GameConstants {
    TILES_DEFAULT_SIZE = 32,
    SCALE = 1.8,
    TILES_IN_WIDTH = 26,
    TILES_IN_HEIGHT = 14,
    TILES_SIZE = Math.floor(TILES_DEFAULT_SIZE * SCALE),
    GAME_WIDTH = TILES_SIZE * TILES_IN_WIDTH,
    GAME_HEIGHT = TILES_SIZE * TILES_IN_HEIGHT,
}
